kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-catalog
  namespace: mskh
  labels:
    app.kubernetes.io/name: simple-catalog
spec:
  replicas: 1
  containers:
    - name: simple-catalog
      image: "sargismarkosyan/kubernetes-ready-app:latest"
      env:
        - name: DBURI
          value: "mongodb://root:root@mongo:27017/simple-catalog?authSource=admin"
        - name: HOME_URL
          value: /simple-catalog/
---
kind: Service
apiVersion: v1
metadata:
  name: simple-catalog
  namespace: mskh
  labels:
    app.kubernetes.io/name: simple-catalog
  annotations:
    description: "https://github.com/sargismarkosyan/kubernetes-ready-app"
spec:
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: simple-catalog
