version: "3.1"

services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
    # ports:
    #   - '27017:27017'

  web:
    build: .
    restart: always
    environment:
      DBURI: mongodb://root:root@mongo:27017/simple-catalog?authSource=admin
      HOME_URL: /
    volumes:
      - ./files:/app/files
    ports:
      - "3000:80"
